### ISSUE TITLE
Publish to RubyGems.org?

### ISSUE THREAD

**Issue by kapoorlakshya** [MacCracken/watir-performance#2]
Hi @MacCracken, just curious whats the possibility of you publishing this gem on rubygems.org? Would give it more exposure and help people consolidate the gem sources.

**Comment by MacCracken** [comment]
its possible, haven't thought about it since its mostly someone else's work.  I mainly have a setup script that builds it for me.

**Comment by kapoorlakshya** [comment]
Your fork works with Watir > v6.0 whereas the original repo relies on `watir-webdriver`, which is no longer maintained. I would be interested in seeing this on RubyGems.org. Here are the steps to publish the gem - http://guides.rubygems.org/publishing/

I am willing to assist with maintaining this if needed.

**Comment by MacCracken** [comment]
0.5.0 has been release to rubygems.... 
/closed

**Comment by kapoorlakshya** [comment]
Thank you very much!
