### ISSUE TITLE
Please relax the Ruby version requirement to be >= 2.0.

### ISSUE THREAD

**Issue by kapoorlakshya** [MacCracken/watir-performance#4]
Hi @MacCracken, can you please consider relaxing the Ruby version requirement to be ` >= 2.0` instead of requiring 2.6?

`s.required_ruby_version = Gem::Requirement.new(">= 2.6.0".freeze)`

Not everyone is on the latest Ruby version, especially in corporate environments where change happens slowly. Unfortunately, we're still on 2.3.3 which restricts me from using the latest version of this gem. Relaxing the requirement to `2.0` will be a big relief for me as I won't have to monkey patch your code in my project. Thank you!

**Comment by MacCracken** [comment]
looking into relaxing it to 2.3.0; which is the best I can do at this point.  Don't really want to support Ruby versions that are EOL.

**Comment by MacCracken** [comment]
@kapoorlakshya try watir-performace v0.9.1; it should be required version of ruby 2.3.0 and up.

**Comment by kapoorlakshya** [comment]
@MacCracken Thanks for doing that. We weren't ready to upgrade from Ruby 2.3 back then, but once we learned that Selenium 4 will require Ruby 2.4 or higher, we swiftly upgraded to Ruby 2.6.

> Don't really want to support Ruby versions that are EOL.

That's understandable. Feel free to change the requirement to 2.4 minimum in the next release. Watir 7 /Selenium 4 will require that anyway.

**Comment by MacCracken** [comment]
@kapoorlakshya no worries; thanks for pointing it out as it was still too strict in terms of required base ruby version.  I was testing for ruby of 2.3.8 to latest prior; so it should be fine with 2.3.0 until next watir/selenium versions.
